version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/middleware/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
