kind: Service
apiVersion: v1
metadata:
  name: rendertron
  namespace: epidemic-com
  labels:
    app: rendertron
    owner: first-impression
spec:
  selector:
    app: rendertron
    owner: first-impression
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8090