apiVersion: v1
kind: ServiceAccount
metadata:
  name: rendertron
  namespace: epidemic-com
  annotations:
    iam.gke.io/gcp-service-account: rendertron@es-platform-prod.iam.gserviceaccount.com
  labels:
    app: rendertron
    owner: first-impression